{% set name = "conda-docker" %}
{% set version = environ.get('GIT_DESCRIBE_TAG', 'untagged')|string|replace('-','_') %}
{% set build_number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: {{ environ.get('FEEDSTOCK_ROOT', '..') }}

build:
  number: {{ build_number }}
  string: {{ [build_number, ('h' + PKG_HASH), environ.get('GIT_DESCRIBE_HASH', '')]|join('_') }}
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [not linux]
  entry_points:
    - conda-docker=conda_docker.cli:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - conda
    - mamba
    - conda-standalone
    - fakechroot

test:
  imports:
    - conda_docker
  commands:
    - conda-docker --help
    - pytest -sv
  requires:
    - pytest
  source_files:
    - tests/

about:
  home: https://github.com/regro/conda-docker
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
