* Docker Envs

Docker Envs is an extension to the docker concept by having
declarative environments that are associated with docker images. In
addition this tool does not require docker to build images. Thus
allowing for interesting caching behavior and tricks that docker would
not normally allow.

** References

 - [[https://docs.docker.com/registry/spec/api/][Docker Registry API Specification]]
 - Docker Image Specification
   - [[https://github.com/moby/moby/blob/master/image/spec/v1.2.md][Summary]]
   - [[https://docs.docker.com/registry/spec/manifest-v2-2/][Registry V2 Specification]]

** Saving a Docker Image for Inspection

Pull and ensure that filesystem exists

#+begin_src python :results none
  from docker_envs.docker.client import pull, save

  pull('continuumio/miniconda3', 'latest')
  save('continuumio/miniconda3', 'latest', '/tmp/miniconda3.tar')
#+end_src

Downloading docker images without docker!

#+begin_src python
  from docker_envs.registry.client import pull_image

  image = 'continuumio/miniconda3'
  tag = 'latest'
  image = pull_image(image, tag)
  images[0].add_layer_path(
      '/home/costrouc/scratch/conda-envs',
      filter=conda_file_filter())

  image.name = 'qwerqwerqwerqwer'
  image.write_file('test.tar')
#+end_src

Modify docker image from filesystem

#+begin_src python :results output
  from docker_envs.docker.base import Image
  from docker_envs.conda import conda_file_filter

  images = Image.from_file('/tmp/miniconda3.tar')
  # images[0].remove_layer()
  images[0].name = 'this-is-a-test'
  images[0].add_layer_path(
      '/home/costrouc/scratch/conda-envs',
      filter=conda_file_filter())
  images[0].add_layer_contents({
      'this/is/a/test1': b'asdfasdf',
      'this/is/a/test2': b'asdfasdf'
  })
  images[0].write_file('example-filter.tar')
#+end_src

#+RESULTS:

Load docker image from the filesystem

#+begin_src python
  from docker_envs.docker.client import load

  load('example.tar')
#+end_src

Conda docker images

#+begin_src python
  from docker_envs.registry.client import pull_image
  from docker_envs.conda import conda_file_filter

  image = 'continuumio/miniconda3'
  tag = 'latest'
  image = pull_image(image, tag)
  image.add_layer_path(
      '/home/costrouc/scratch/conda-envs',
      filter=conda_file_filter())
  image.name = 'qwerqwerqwerqwer'
  image.write_file('test.tar')
#+end_src

#+RESULTS:

#+begin_src shell
  python -m docker_envs build -b continuumio/miniconda3:latest -o docker-envs.tar
#+end_src

#+RESULTS:

#+begin_src shell

#+end_src

#+RESULTS:
| docker_envs        |
| docker-envs.tar    |
| example-filter.tar |
| example.tar        |
| README.md          |
| #README.org#       |
| README.org         |
| shell.nix          |
| test.tar           |
