name: "Tests"

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  tests:
    name: "Test conda-docker"
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: conda-docker-dev
          environment-file: environment-dev.yaml
          auto-activate-base: false

      - name: Install conda-docker
        run: |
          pip install .

      - name: Conda environment information
        run: |
          conda info
          conda list

      - name: Black Formatting
        run: |
          black --version
          black conda_docker tests --diff
          black --check conda_docker tests

      - name: Flake8 formatting
        run: |
          flake8 --version
          flake8

      - name: Release Check
        run: |
          python -m build --sdist
          twine check dist/*

      - name: Unit Tests
        run: |
          pytest

      - name: CLI Tests
        run: |
          conda-docker --help
          conda-docker build -n conda-docker-dev -i conda-docker-dev-1:latest -o conda-docker-dev-1.docker.tar
          docker load --input conda-docker-dev-1.docker.tar
          docker images
          docker run conda-docker-dev-1:latest python -c "import conda; import sys; print(sys.version_info); print('I ran conda-docker-dev-1')"
          echo "finished conda-docker-dev-1"

          conda-docker build -i conda-docker-dev-2:latest -o conda-docker-dev-2.docker.tar numpy python==3.10
          docker load --input conda-docker-dev-2.docker.tar
          docker images
          docker run conda-docker-dev-2:latest python -c "import numpy; import sys; print(sys.version_info); print('I ran conda-docker-dev-2')"
          echo "finished conda-docker-dev-2"
